Inscription detail template + Routes + Refactoring (#103)
* Routes + refactoring

* Fix inscription image url

* vscode: formatOnSave

* Content + style

* Clean up

* Fullscreen layer + some styling

* Fix: Preview layer not visible (Firefox only)

* Fix class prop

* Remove `i0`

Related to #59

* Fix cycling of inscriptions in LiveGrid

* WIP: Trying to fix render updates in `For` component

Still get `Panicked at 'already mutably borrowed: BorrowError' errors`

* Fix rendering + updates in `For`

* Optimize release build

based on https://leptos-rs.github.io/leptos/appendix_binary_size.html#things-to-do

* Address review suggestions

* Remove `isDev` label + cargo fmt

* Mock inscription 0

* zero-width space

by following https://discord.com/channels/1031524867910148188/1102915498817097821/1103016461582209134